version: '3.5'
services:
  py-srv:
    build: py-srv
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=db:9042
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30

  db:
    image: cassandra:latest
    ports:
      - 9042
    healthcheck:
      test: [ "CMD", "ls", "/opt/cassandra/bin" ]
      interval: 15s
      timeout: 10s
      retries: 10
    environment:
      - CASSANDRA_SEEDS=node2,node3
      - CASSANDRA_CLUSTER_NAME=citizix
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch 
      - CASSANDRA_DC=datacenter1
  
  node2:
    image: cassandra:latest
    ports:
      - 9042
    healthcheck:
      test: [ "CMD", "ls", "/opt/cassandra/bin" ]
      interval: 15s
      timeout: 10s
      retries: 10
    environment:
      - CASSANDRA_CLUSTER_NAME=citizix
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch 
      - CASSANDRA_DC=datacenter1
  
  node3:
    image: cassandra:latest
    ports:
      - 9042
    healthcheck:
      test: [ "CMD", "ls", "/opt/cassandra/bin" ]
      interval: 15s
      timeout: 10s
      retries: 10
    environment:
      - CASSANDRA_CLUSTER_NAME=citizix
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch 
      - CASSANDRA_DC=datacenter1